import type { Metadata } from "next";
import { IBM_Plex_Serif } from "next/font/google";
import SiteHeader from "./site-header";
import ThemeToggle from "./theme-toggle";
import "./globals.css";
import "katex/dist/katex.min.css";

const ibmPlexSerif = IBM_Plex_Serif({
  variable: "--font-ibm-plex-serif",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Toby Purbojo",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibmPlexSerif.variable} antialiased`}>
        <SiteHeader />
        <div className="page-content">{children}</div>
        <footer className="site-mark">TOBY PURBOJO @ 2025</footer>
        <ThemeToggle />
      </body>
    </html>
  );
}
